### PR TITLE
Time format updated in Upcoming Tab

### LINKED ISSUE #65: Change time format
In upcoming tab show time in 12 hour format.

### PR DESCRIPTION
**Pull request by neeraj-2**
Fixes #65 , the time format has been updated to 12-hour format in `Upcoming `Tab
Demo:
image

### CODE REVIEW

**Comment by DarshitJain04** [comment]
> Fixes #65 , the time format has been updated to 12-hour format in `Upcoming `Tab
> Demo:
> image

@neeraj-2 why does the upcoming alarm shows only the name course code? It was changed to course code and course name, isn't it?

**Comment by hirenchalodiya1** [comment]
> > Fixes #65 , the time format has been updated to 12-hour format in `Upcoming `Tab
> > Demo:
> > image
> 
> @neeraj-2 why does the upcoming alarm shows only the course code? It was changed to course code and course name, isn't it?
I think he hasn't pulled the latest code

**Comment by DarshitJain04** [comment]
> > > Fixes #65 , the time format has been updated to 12-hour format in `Upcoming `Tab
> > > Demo:
> > > image
> > 
> > 
> > @neeraj-2 why does the upcoming alarm shows only the course code? It was changed to course code and course name, isn't it?
> > I think he hasn't pulled the latest code

Yeah exactly! @neeraj-2 make sure you pull recent changes to update your repo

**Comment by neeraj-2** [comment]
> @neeraj-2 it seems in your second commit you just added space before and after the `=` sign.
> I'd suggest you to use prettier to format the code. I did mention this in your previous PR also.

Sure @DarshitJain04 I will take care ahead!

**Comment by hirenchalodiya1** [comment]
@anshulahuja98 can you check whether the issue has been fixed or not?

**Pull request merged**
