### PR TITLE
added accordian in alarmup section with today,tomorrow and later

### LINKED ISSUE #54: Make category in upcoming
Make collapsable categories in upcoming.
Like Today, Tomorrow, and then date wise

### PR DESCRIPTION
**Pull request by utkarsh4321**
Hii first I want to say thanks for this great opportunity. 
I hope I worked according to your requirements

I added accordion in alarm up section as per your requirements as I understood.
Please accept my PR. If you got any problem. Ping me I will try to solve it asap.
Fixes #54

### CODE REVIEW

**Comment by hirenchalodiya1** [comment]
image

@utkarsh4321 size of popup should not change. in both scenarios size is different and also different from other tabs as well

image

**Comment by DarshitJain04** [comment]
@utkarsh4321 do not make changes to `Popup/index.css`
You can access the class and add styles in the file itself

**Comment by utkarsh4321** [comment]
Hii @DarshitJain04 can you tell me how i will make accordion height dynamic tell me if you had any idea regarding this so I will solve it asap

**Comment by DarshitJain04** [comment]
> Hii @DarshitJain04 can you tell me how i will make accordion height dynamic tell me if you had any idea regarding this so I will solve it asap

Try working with flex and overflow properties. It should work
Like maybe give overflow property to the parent element and fixed height to it so when the list collapse, the size of the parent remains the same.

**Comment by DarshitJain04** [comment]
> @utkarsh4321 do not make changes to `Popup/index.css`
> You can access the class and add styles in the file itself
> 
> Screenshot 2020-10-06 222903
> Also, here the size of the accordion is larger than the number of alarms present. Like make it such that there is no extra space left and the collapsed accordion ends where the last alarm ends

@utkarsh4321 I'm not sure why there's some extra space left after the alarms. Try finding the bug using dev console, might help!

**Comment by utkarsh4321** [comment]
Ok

**Comment by utkarsh4321** [comment]
Hi @DarshitJain04 i did some changes according to your requirements. Please review it and let me know if there is any problem.

**Comment by DarshitJain04** [comment]
> Hi @DarshitJain04 i did some changes according to your requirements. Please review it and let me know if there is any problem.

Hey @utkarsh4321 great work on UI
There's one problem, the alarm toggle doesn't work in the upcoming alarms ( The tick mark on the left in the upcoming alarms )
Please have a look at it
Everything else it perfect!

**Comment by DarshitJain04** [comment]
> > Hi @DarshitJain04 i did some changes according to your requirements. Please review it and let me know if there is any problem.
> 
> Hey @utkarsh4321 great work on UI
> There's one problem, the alarm toggle doesn't work in the upcoming alarms ( The tick mark on the left in the upcoming alarms )
> Please have a look at it
> Everything else it perfect!

The console shows `can not read property '0' of undefined`

**Comment by DarshitJain04** [comment]
@utkarsh4321 The `updatestatus` tries to use the variable `alarms`
https://github.com/devlup-labs/meet-scheduler/blob/9e37ebe3578f29de49acde4297f4e24595fab4e9/src/pages/Popup/components/AlarmUp.jsx#L59

But now there's now such variable in the state and I guess because of when you try to toggle, it shows undefined

**Comment by utkarsh4321** [comment]
ok i will check it and solve asap

**Comment by utkarsh4321** [comment]
Hii @DarshitJain04 i fix the toggle functionality problem into upcoming alarms. Please check it and let me know if there is any problem i will try to fix it asap.

**Comment by DarshitJain04** [comment]
Hey @utkarsh4321 it's working completely fine now! Really great work!
Thank you for your contribution! We'll merge this PR now

@hirenchalodiya1 this PR is ready for merge

**Review by DarshitJain04 — APPROVED** [review]

**Review by hirenchalodiya1 — APPROVED** [review]

**Comment by hirenchalodiya1** [comment]
Merged !!
@utkarsh4321 thanks for contribution

**Comment by utkarsh4321** [comment]
Thanks to you guys for this great opportunity 🙏. if there is anything else
that I can do please let me know.

**Pull request merged**
